---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtools-trace
spec:
  selector:
    matchLabels:
      app: webtools-trace
  replicas: 1
  template:
    metadata:
      labels:
        app: webtools-trace
    spec:
      containers:
      - name: webtools-trace
        image: "openzipkin/zipkin:latest"
        imagePullPolicy: Always
        ports:
          - containerPort: 9411
---
apiVersion: v1
kind: Service
metadata:
  name: webtools-trace
spec:
  selector:
    app: webtools-trace
  ports:
  - protocol: "TCP"
    port: 8187
    targetPort: 9411
  type: NodePort